version: "3"
services:
  ruby-back:
    build:
      context: /home/aslan/REACT_RUBY_NGINX/rails-realworld-example-app
      dockerfile: Dockerfile
    image: ruby_image
    container_name: ruby_app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - 80:80
    volumes:
      - /etc/var/log:/var/log/nginx
  react-front:
    build:
      context: /home/aslan/REACT_RUBY_NGINX/realworld-example
      dockerfile: Dockerfile
    image: react-front
    container_name: react_app
